import { Geist, Geist_Mono } from "next/font/google";
import Aside from "@/layouts/Aside";
import Header from "@/layouts/Header";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Movie Project",
  description: "Generated by Vanda as a Project",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}suppressHydrationWarning={true}>
        <div id="test-body">
        <div className="main-container">
            <Aside />
            <Header />        
          <main className="content-area">
            {children}
          </main>
        </div>
        </div>
      </body>
    </html>
  );
}
